# CircleCI configuration file

version: 2.1
orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@2.4.0
  node: circleci/node@5.0.2
jobs:
  build:
    machine: true
    parallelism: 4
    steps:
      - git-shallow-clone/checkout
      - restore_cache:
          keys:
            - v1-dependency-{{ checksum "package-lock.json" }}
            - v1-dependency-
      - run: docker run --name=writer -e MYSQL_ROOT_PASSWORD=1234 -e MYSQL_DATABASE=writer -p 6603:3306 -d mysql:8.0
      - node/install:
          node-version: "16.15"
      - run:
          command: |
            touch .env
            echo "test=$test" > .env
      - run: node --version
      - run: npm ci
      - save_cache:
          key: v1-dependency-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          command: |
            npx jest
